language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install Jinja2 PyYAML
  - pip install 'flake8<3.8' Sphinx com.wyattbaldwin.make_release
  - pip install .
script:
  - python -m unittest discover
  - flake8 .
  - sphinx-build -E docs docs/_build
