[mypy]
files = src/runcommands

; NOTE: This is required because arg() isn't considered a valid annotation.
; TODO: Use a valid annotation style.
disable_error_code = valid-type

[mypy-cached_property]
ignore_missing_imports = True
