[tox]
envlist = py311,py312,py313,py314
isolated_build = true

[testenv]
deps =
    .
    mypy>=1.20.0
    types-toml>=0.10.8.20260408
    ruff>=0.15.10
    com.wyattbaldwin.make_release>=1.0a4
commands =
    python -m unittest discover .
    ruff check .
    ruff format --check .
    mypy
