[tox]
envlist = py310,py311,3.12,3.13,3.14
isolated_build = true

[testenv]
deps =
    .
    ruff>=0.15.1
    com.wyattbaldwin.make_release>=1.0a4
commands =
    python -m unittest discover .
    ruff check .
    ruff format --check .
